#!/bin/sh
#
# move a draft to published post, to be posted on a given date
#  publish [-n] date drafts....
# the date is anything accepted by the 'date' command, common constructs:
#  14-Sep-1899, +2 weeks, now
#
if [ $1 = "-n" ]
then
    NOOP=echo
    shift;
else
    NOOP=
fi

# figure out the date to publish
# hugo is fussy about timezone spec
pubdate="$1"; shift;
pubdateiso=`date +%FT%T%:z --date "$pubdate"`
pubdatefile=`date +%F --date "$pubdate"`
if [ -z "$pubdateiso" ]
then
    echo Error: unable to parse date spec $pubdate >&2
    exit 1
fi

# it doesn't make much sense to publish several things at at the same time
# but no reason to forbid it :)
for draft in $*
do
    test -e $draft || draft=content/draft/$draft
    test -e $draft || { echo Error: cannot find draft $draft >&2; exit 1; }

    pubdest=content/post/$pubdatefile-`basename $draft`
    if [ -f $draft ]
    then
        pubfile=content/post/$pubdatefile-`basename $draft`
    else
        pubfile=content/post/$pubdatefile-`basename $draft`/index.md
    fi
    
    echo "Publishing to $pubdest on $pubdateiso"

    # do this before messing with the file.
    # if it's a directory we need it moved into place first,
    # if it is a file, we will overwrite it in the next step
    $NOOP git mv $draft $pubdest

    # remove draft setting
    # insert/change both date and published date to be the same
    (
	echo 'draft = "false"'
	echo 'date = "'$pubdateiso'"'
	echo 'publishdate = "'$pubdateiso'"'
        if [ -z "$NOOP" ]; then cat $pubfile; fi ) |
        if [ "$NOOP" ]
        then
            cat | head -3
            echo NOOP: write to $pubfile
        else
            perl -ne 'BEGIN { print "+++\n"; } if (/^\+\+\+/ and not $seen{$_}++) { } elsif (/^(\w+)\s*=\s*/) { !$seen{$1}++ && print } else {print}' > /tmp/pp$$
            cp /tmp/pp$$ $pubfile && rm /tmp/pp$$
        fi
done

