name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '17 12 * * 4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install lftp

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1

    - name: Get Hugo
      run: make hugo

    - name: generate site
      run: make generate

    - uses: extractions/netrc@v1
      with:
        machine: ftp.veganmilitia.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

    - name: upload
      run: make upload
