name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install lftp
      run: apt install lftp

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1

    - name: Get Hugo
      run: make hugo

    - name: generate site
      run: make generate

    - name: upload
      run: make upload
